# Managing Conda Environment

## Creating environment 
- Optionally, specify a python version
```bash
conda create --name env-name python==version
```

## Activating and deactivating
```bash
conda activate env-name
conda deactivate
```

## Listing all environment
```bash
conda env list
conda info --envs
```

## Removing environment
```bash
conda env remove -n env_name
```

## Installing packages in the current env
```bash
conda install pkg_name==version
```

## Listing packages 
In the current environment
```bash
conda list
```

In the specified environment
```bash
conda list -n env-name
```

## Reproducing an environment
### Produce a spec list
```
conda list --explicit
```

### Create env spec file 
```bash
conda list --explicit > spec-file.txt
```

### Creating an environment from a file  
```
conda create --name env-name --file spec-file.txt
```

Example output
```bash
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/osx-64/gh-2.5.2-h990441c_0.tar.bz2
https://conda.anaconda.org/bioconda/osx-64/sra-tools-2.8.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/_r-mutex-1.0.1-anacondar_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/_r-xgboost-mutex-2.0-cpu_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/aws-c-common-0.6.2-h0d85af4_0.tar.bz2
https://conda.anaconda.org/bioconda/osx-64/bmfilter-3.101-3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/bzip2-1.0.8-h0d85af4_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/c-ares-1.18.1-h0d85af4_0.tar.bz2
```
> The list can be very long depending on the content of the env.

## Sharing environment across platforms
- Export from history by adding --from-history

### Export the history of source
```bash
conda env export --from-history > environment.yml
```
The `environment.yml` file may contain similar info like so:
```bash
name: env-name
channels:
  - biobakery
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
prefix: /Users/username/opt/anaconda3/envs/env-name
```

### Re-creating the environment
```bash
conda env create -f environment.yml
```

## Rollback to conda revisions
- Conda stores changes made using the conda commands. 
- We can roll back changes by using revision numbers.

Conda revisions and revision numbers
```bash
conda list --revisions
```

Example output
```bash
2022-09-20 19:58:49  (rev 0)
    +bzip2-1.0.8 (conda-forge/osx-64)
    +ca-certificates-2022.9.14 (conda-forge/osx-64)
    +libffi-3.4.2 (conda-forge/osx-64)
    +libsqlite-3.39.3 (conda-forge/osx-64)
    +libzlib-1.2.12 (conda-forge/osx-64)
    +ncurses-6.3 (conda-forge/osx-64)
    +openssl-3.0.5 (conda-forge/osx-64)
    +pip-22.2.2 (conda-forge/noarch)
    +python-3.10.6 (conda-forge/osx-64)
    +readline-8.1.2 (conda-forge/osx-64)
    +setuptools-65.3.0 (conda-forge/noarch)
    +tk-8.6.12 (conda-forge/osx-64)
    +tzdata-2022c (conda-forge/noarch)
```

## Restoring previous revision
```bash
conda install --rev 0
```

> I will continue adding useful info whenever found.

# Conda Troubleshooting

## CommandNotFoundError
- CommandNotFoundError: Your shell has not been properly configured to use ‘conda activate’
- **Solution**: Run the following sequentially
```
source activate
conda deactivate
conda activate desired-env-name
```

## Useful references
- Managing conda virtual environment [@SelvaCondaEnv2022]
- [@conda2022]
- [@anaconda2020]
- [@anaconda2022]
- [@miniconda2022]

